---
- name: Ansible Playbook to Install and Setup Apache on Ubuntu
  hosts: webservers
  tasks:
    - name: Install latest version of Apache
      command: sudo mkdir /home/ec2-user/pqwe
      
    - name: Copy your index file
      template:
        src: "index.html"
        dest: "/var/www/html/"
...
