---
- name: Ansible Playbook to Install and Setup Apache on Ubuntu
  hosts: webservers
  become: yes
  tasks:
    - name: Install latest version of Apache
      apt: name=apache2 update_cache=yes state=latest
      
    - name: Copy your index file
      template:
        src: "index.html"
        dest: "/var/www/html/"
...
